import json

papers = [
    {
        "id": "pub-1",
        "title": "Secure Real Time Heterogeneous Data Management Tool",
        "venue": "IEEE International Conference on Cognitive Machine Learning (CogML)",
        "year": "2019",
        "authors": "Harsh Verma",
        "category": "conference",
        "category_label": "IEEE Conference",
        "topic": "iot",
        "topic_label": "IoT & Edge Computing",
        "doi": "10.1109/CogML.2019.9014355",
        "link": "https://ieeexplore.ieee.org/document/9014355",
        "publisher": "IEEE Xplore",
        "abstract": "Presents a novel architecture addressing the complexity of ingesting, validating, and managing real-time streaming data from heterogeneous IoT devices in parallel. Formulates a secure, low-latency edge-computing ingestion pipeline capable of sub-millisecond dispatch and tamper-evident stream verification.",
        "tags": ["IEEE", "IoT Edge Computing", "Data Management", "Real-Time Systems", "Security"],
        "bibtex": """@inproceedings{verma2019secure,
  title={Secure Real Time Heterogenous Data Management Tool},
  author={Verma, Harsh},
  booktitle={2019 IEEE International Conference on Cognitive Machine Learning (CogML)},
  pages={1--6},
  year={2019},
  organization={IEEE},
  doi={10.1109/CogML.2019.9014355}
}"""
    },
    {
        "id": "pub-2",
        "title": "Real Time Analytics Performance Load Simulation and Scaling",
        "venue": "International Journal of Computer Applications (IJCA)",
        "year": "2017",
        "volume": "Vol. 176, No. 2",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "performance",
        "topic_label": "Performance & Scaling",
        "doi": "10.5120/ijca2017915532",
        "link": "https://www.ijcaonline.org/archives/volume176/number2/28523-2017915532/",
        "publisher": "IJCA Online",
        "abstract": "Investigates performance benchmarking, simulated multi-tenant load characteristics, and horizontal auto-scaling algorithms for real-time analytics engines handling millions of concurrent metric streams with sustained throughput guarantees.",
        "tags": ["Load Simulation", "Real-Time Analytics", "Distributed Systems", "Cloud Scaling", "Benchmarking"],
        "bibtex": """@article{verma2017real,
  title={Real Time Analytics Performance Load Simulation and Scaling},
  author={Verma, Harsh},
  journal={International Journal of Computer Applications},
  volume={176},
  number={2},
  pages={1--7},
  year={2017},
  publisher={Foundation of Computer Science},
  doi={10.5120/ijca2017915532}
}"""
    },
    {
        "id": "pub-3",
        "title": "Explainable AI (XAI) for Software Engineering Decision-Making",
        "venue": "International Journal of Innovative Research in Computer and Communication Engineering (IJIRCCE)",
        "year": "2024",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "software_eng",
        "topic_label": "Software Engineering & AI",
        "doi": "10.15680/IJIRCCE.2024.1205018",
        "link": "https://www.ijircce.com/article/explainable-ai-xai-for-software-engineering-decision-making-18479",
        "alt_link": "https://www.researchgate.net/publication/401693316_Explainable_AI_XAI_for_Software_Engineering_Decision-Making",
        "alt_label": "ResearchGate",
        "publisher": "IJIRCCE / ResearchGate",
        "abstract": "Explores interpretable machine learning frameworks integrated into DevOps, automated CI/CD code reviewing, and architecture decision-making, providing engineering leadership with actionable rationale and trust mechanisms behind automated AI recommendations.",
        "tags": ["Explainable AI", "XAI", "Software Engineering", "Decision Support", "DevOps AI"],
        "bibtex": """@article{verma2024explainable,
  title={Explainable AI (XAI) for Software Engineering Decision-Making},
  author={Verma, Harsh},
  journal={International Journal of Innovative Research in Computer and Communication Engineering (IJIRCCE)},
  volume={12},
  pages={18479--18486},
  year={2024},
  publisher={IJIRCCE}
}"""
    },
    {
        "id": "pub-4",
        "title": "Ethical Challenges and Bias Mitigation in Artificial Intelligence Systems",
        "venue": "World Journal of Advanced Research and Reviews (WJARR)",
        "year": "2025",
        "volume": "Vol. 28, No. 3",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "ethics",
        "topic_label": "AI Ethics & Governance",
        "doi": "10.30574/wjarr.2025.28.3.3904",
        "link": "https://wjarr.com/content/ethical-challenges-and-bias-mitigation-artificial-intelligence-systems",
        "publisher": "WJARR",
        "abstract": "Examines systemic algorithmic bias, training dataset imbalances, and demographic disparities in enterprise machine learning pipelines, proposing a mathematical governance framework for continuous fairness verification and bias mitigation at scale.",
        "tags": ["AI Ethics", "Bias Mitigation", "Algorithmic Fairness", "AI Governance", "Responsible AI"],
        "bibtex": """@article{verma2025ethical,
  title={Ethical Challenges and Bias Mitigation in Artificial Intelligence Systems},
  author={Verma, Harsh},
  journal={World Journal of Advanced Research and Reviews},
  volume={28},
  number={3},
  pages={3904--3915},
  year={2025},
  publisher={WJARR},
  doi={10.30574/wjarr.2025.28.3.3904}
}"""
    },
    {
        "id": "pub-5",
        "title": "Cloud-Based AI Systems for Scalable and Intelligent Software Applications",
        "venue": "World Journal of Advanced Research and Reviews (WJARR)",
        "year": "2026",
        "volume": "Vol. 29, No. 1",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "cloud_ai",
        "topic_label": "Cloud & Infrastructure",
        "doi": "10.30574/wjarr.2026.29.1.0077",
        "link": "https://wjarr.com/content/cloud-based-ai-systems-scalable-and-intelligent-software-applications",
        "publisher": "WJARR",
        "abstract": "Proposes unified architectural patterns for deploying foundation models and deep learning inference workloads across distributed multi-region cloud infrastructures with sub-second response times and elastic compute orchestration.",
        "tags": ["Cloud AI", "Scalable Systems", "Distributed Compute", "Intelligent Applications", "MLOps"],
        "bibtex": """@article{verma2026cloud,
  title={Cloud-Based AI Systems for Scalable and Intelligent Software Applications},
  author={Verma, Harsh},
  journal={World Journal of Advanced Research and Reviews},
  volume={29},
  number={1},
  pages={77--89},
  year={2026},
  publisher={WJARR},
  doi={10.30574/wjarr.2026.29.1.0077}
}"""
    },
    {
        "id": "pub-6",
        "title": "AI-Driven Cybersecurity in Software Engineering",
        "venue": "World Journal of Advanced Research and Reviews (WJARR)",
        "year": "2025",
        "volume": "Vol. 27, No. 3",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "Cybersecurity & Defenses",
        "doi": "10.30574/wjarr.2025.27.3.3347",
        "link": "https://wjarr.com/content/ai-driven-cybersecurity-software-engineering",
        "publisher": "WJARR",
        "abstract": "Analyzes the synergy between deep neural network anomaly detection and automated security pipelines in SDLC, demonstrating automated zero-day detection, code vulnerability identification, and intelligent threat remediation.",
        "tags": ["AI Cybersecurity", "Software Security", "Vulnerability Detection", "SDLC Security", "Threat Intelligence"],
        "bibtex": """@article{verma2025aidriven,
  title={AI-Driven Cybersecurity in Software Engineering},
  author={Verma, Harsh},
  journal={World Journal of Advanced Research and Reviews},
  volume={27},
  number={3},
  pages={3347--3358},
  year={2025},
  publisher={WJARR},
  doi={10.30574/wjarr.2025.27.3.3347}
}"""
    },
    {
        "id": "pub-7",
        "title": "Future Trends in AI, Machine Learning, and Big Data: Implications for Technical Leadership",
        "venue": "International Journal of Engineering & Extended Technologies Research (IJEETR)",
        "year": "2025",
        "volume": "Vol. 7, No. 4",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "leadership",
        "topic_label": "Tech Leadership & Trends",
        "doi": "10.15662/IJEETR.2025.0704017",
        "link": "https://www.ijeetr.com/index.php/ijeetr/article/view/925",
        "publisher": "IJEETR",
        "abstract": "Provides a strategic roadmap for engineering executives and CTOs on navigating technological shifts in generative foundation models, high-volume streaming data architectures, and organizational multi-agent team transformations.",
        "tags": ["Technical Leadership", "AI Trends", "Big Data", "Engineering Strategy", "Future ML"],
        "bibtex": """@article{verma2025future,
  title={Future Trends in AI, Machine Learning, and Big Data: Implications for Technical Leadership},
  author={Verma, Harsh},
  journal={International Journal of Engineering \& Extended Technologies Research},
  volume={7},
  number={4},
  pages={17--28},
  year={2025},
  publisher={IJEETR},
  doi={10.15662/IJEETR.2025.0704017}
}"""
    },
    {
        "id": "pub-8",
        "title": "Agentic Workflows for End-to-End Software Engineering Automation",
        "venue": "World Journal of Advanced Research and Reviews (WJARR)",
        "year": "2025",
        "volume": "Vol. 25, No. 3",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "agents",
        "topic_label": "AI Agentic Systems",
        "doi": "10.30574/wjarr.2025.25.3.0887",
        "link": "https://wjarr.com/content/agentic-workflows-end-end-software-engineering-automation",
        "publisher": "WJARR",
        "abstract": "Presents an end-to-end framework leveraging autonomous multi-agent systems to execute requirements engineering, architecture drafting, test-driven synthesis, and production deployment cycles without human-in-the-loop bottlenecks.",
        "tags": ["Agentic Workflows", "Software Automation", "Autonomous Agents", "Code Synthesis", "SDLC Automation"],
        "bibtex": """@article{verma2025agentic,
  title={Agentic Workflows for End-to-End Software Engineering Automation},
  author={Verma, Harsh},
  journal={World Journal of Advanced Research and Reviews},
  volume={25},
  number={3},
  pages={887--899},
  year={2025},
  publisher={WJARR},
  doi={10.30574/wjarr.2025.25.3.0887}
}"""
    },
    {
        "id": "pub-9",
        "title": "Economic Impact and Productivity Modeling of AI Agents",
        "venue": "World Journal of Advanced Research and Reviews (WJARR)",
        "year": "2025",
        "volume": "Vol. 26, No. 3",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "agents",
        "topic_label": "AI Agentic Systems",
        "doi": "10.30574/wjarr.2025.26.3.2304",
        "link": "https://wjarr.com/content/economic-impact-and-productivity-modeling-ai-agents",
        "publisher": "WJARR",
        "abstract": "Develops a quantitative econometric productivity model mapping the integration of autonomous AI agents across modern software enterprises, measuring developer velocity multipliers and total cost of ownership reductions.",
        "tags": ["Economic Impact", "Productivity Modeling", "AI Agents", "ROI Analysis", "Enterprise AI"],
        "bibtex": """@article{verma2025economic,
  title={Economic Impact and Productivity Modeling of AI Agents},
  author={Verma, Harsh},
  journal={World Journal of Advanced Research and Reviews},
  volume={26},
  number={3},
  pages={2304--2317},
  year={2025},
  publisher={WJARR},
  doi={10.30574/wjarr.2025.26.3.2304}
}"""
    },
    {
        "id": "pub-10",
        "title": "AI Agentic Architectures for Autonomous Data Engineering Pipelines",
        "venue": "International Journal of Research and Applied Innovations (IJRAI)",
        "year": "2024",
        "volume": "Vol. 7, No. 6",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "agents",
        "topic_label": "AI Agentic Systems",
        "doi": "10.15662/IJRAI.2024.0706041",
        "link": "https://ijrai.org/index.php/ijrai/article/view/589",
        "publisher": "IJRAI",
        "abstract": "Details dynamic autonomous agent configurations that automatically synthesize ETL/ELT pipelines, validate real-time schema drifts, reconcile corrupted data partitions, and optimize query workloads in cloud data lakes.",
        "tags": ["Data Engineering", "Autonomous ETL", "Agentic Architecture", "Schema Drift", "Data Lakehouse"],
        "bibtex": """@article{verma2024agenticdata,
  title={AI Agentic Architectures for Autonomous Data Engineering Pipelines},
  author={Verma, Harsh},
  journal={International Journal of Research and Applied Innovations},
  volume={7},
  number={6},
  pages={41--52},
  year={2024},
  publisher={IJRAI},
  doi={10.15662/IJRAI.2024.0706041}
}"""
    },
    {
        "id": "pub-11",
        "title": "Autonomous Multi-Agent Systems for Enterprise Decision-Making",
        "venue": "International Journal of Engineering & Extended Technologies Research (IJEETR)",
        "year": "2024",
        "volume": "Vol. 6, No. 5",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "agents",
        "topic_label": "AI Agentic Systems",
        "doi": "10.15662/IJEETR.2024.0605021",
        "link": "https://ijeetr.com/index.php/ijeetr/article/view/958/895",
        "publisher": "IJEETR",
        "abstract": "Introduces a collaborative multi-agent voting and deliberation hierarchy designed for high-consequence enterprise decision scenarios, ensuring consensus formation, verification, and auditability across heterogeneous models.",
        "tags": ["Multi-Agent Systems", "Enterprise Decision-Making", "Consensus Protocol", "Autonomous AI", "Governance"],
        "bibtex": """@article{verma2024autonomousmultiagent,
  title={Autonomous Multi-Agent Systems for Enterprise Decision-Making},
  author={Verma, Harsh},
  journal={International Journal of Engineering \& Extended Technologies Research},
  volume={6},
  number={5},
  pages={21--33},
  year={2024},
  publisher={IJEETR},
  doi={10.15662/IJEETR.2024.0605021}
}"""
    },
    {
        "id": "pub-12",
        "title": "Security in Multi-Agent AI Systems: Modeling Emergent Vulnerabilities via Trust Graphs",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 4",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v14i04.ec04",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/6666",
        "publisher": "IJSRM",
        "abstract": "Constructs dynamic trust graph formalisms to evaluate privilege escalation, lateral prompt injection, and cascading failure propagation across distributed multi-agent collaborative networks.",
        "tags": ["Trust Graphs", "Multi-Agent Security", "Vulnerability Modeling", "Emergent Behavior", "Prompt Injection"],
        "bibtex": """@article{verma2026securitytrustgraphs,
  title={Security in Multi-Agent AI Systems: Modeling Emergent Vulnerabilities via Trust Graphs},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={4},
  pages={ec04},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i04.ec04}
}"""
    },
    {
        "id": "pub-13",
        "title": "Clean Attacks: Formalizing Semantically Valid Adversarial Behavior in Autonomous AI Agent Systems",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2025",
        "volume": "Vol. 13, No. 10",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v13i10.ec03",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/6755",
        "publisher": "IJSRM",
        "abstract": "Defines and categorizes 'Clean Attacks'—adversarial inputs that bypass syntactical and semantic guardrails by strictly obeying schema and policy specifications while manipulating agent objective functions.",
        "tags": ["Clean Attacks", "Adversarial AI", "Semantic Exploits", "Agent Safety", "Guardrails"],
        "bibtex": """@article{verma2025cleanattacks,
  title={Clean Attacks: Formalizing Semantically Valid Adversarial Behavior in Autonomous AI Agent Systems},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={13},
  number={10},
  pages={ec03},
  year={2025},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v13i10.ec03}
}"""
    },
    {
        "id": "pub-14",
        "title": "Designing Self-Healing AI Agentic Systems: A Framework for Autonomous Detection and Response",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 6",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "agents",
        "topic_label": "AI Agentic Systems",
        "doi": "10.18535/ijsrm/v14i06.ec3",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/6868",
        "publisher": "IJSRM",
        "abstract": "Develops closed-loop supervisory controller architectures allowing agent swarms to monitor runtime drift, self-quarantine compromised agents, and synthesize remediation routines dynamically.",
        "tags": ["Self-Healing Systems", "Autonomous Detection", "Fault Recovery", "Resilient AI", "Supervisory Control"],
        "bibtex": """@article{verma2026selfhealing,
  title={Designing Self-Healing AI Agentic Systems: A Framework for Autonomous Detection and Response},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={6},
  pages={ec3},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i06.ec3}
}"""
    },
    {
        "id": "pub-15",
        "title": "Intent-Based Security: Replacing Identity-Centric Trust in Autonomous AI Agentic Systems",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 6",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v14i06.ec3",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/6977",
        "publisher": "IJSRM",
        "abstract": "Proves that traditional identity and RBAC paradigms fail under dynamic agent delegation, proposing an intent-based cryptographic capability protocol that evaluates purpose before granting execution privileges.",
        "tags": ["Intent-Based Security", "Zero Trust", "Agent Identity", "Access Control", "Cryptographic Capabilities"],
        "bibtex": """@article{verma2026intentsecurity,
  title={Intent-Based Security: Replacing Identity-Centric Trust in Autonomous AI Agentic Systems},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={6},
  pages={ec3},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i06.ec3}
}"""
    },
    {
        "id": "pub-16",
        "title": "Policy Drift in Learning AI Agents: A Dynamical Systems Perspective on Security Degradation",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2025",
        "volume": "Vol. 13, No. 7",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v13i07.ec08",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/6710",
        "publisher": "IJSRM",
        "abstract": "Models online reinforcement learning agents through the lens of non-linear dynamical systems, quantifying how incremental reward exploitation leads to safety policy erosion and boundary violations over time.",
        "tags": ["Policy Drift", "Dynamical Systems", "Security Degradation", "Reinforcement Learning", "AI Safety"],
        "bibtex": """@article{verma2025policydrift,
  title={Policy Drift in Learning AI Agents: A Dynamical Systems Perspective on Security Degradation},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={13},
  number={7},
  pages={ec08},
  year={2025},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v13i07.ec08}
}"""
    },
    {
        "id": "pub-17",
        "title": "Toward a Unified Security Systems Theory for Autonomous AI Systems",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 6",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v14i06.ec4",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/7251",
        "publisher": "IJSRM",
        "abstract": "Synthesizes control theory, cybernetics, and computer security into a holistic mathematical foundation for evaluating invariants, failure bounds, and safety margins across autonomous AI software systems.",
        "tags": ["Security Systems Theory", "Unified Framework", "Autonomous AI", "Cybernetics", "Safety Bounds"],
        "bibtex": """@article{verma2026unifiedtheory,
  title={Toward a Unified Security Systems Theory for Autonomous AI Systems},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={6},
  pages={ec4},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i06.ec4}
}"""
    },
    {
        "id": "pub-18",
        "title": "AI-Powered Anomaly Detection in Cloud-Based Applications",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2024",
        "volume": "Vol. 12, No. 1",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "cloud_ai",
        "topic_label": "Cloud & Infrastructure",
        "doi": "10.18535/ijsrm/v12i01.ec07",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/4774",
        "publisher": "IJSRM",
        "abstract": "Presents real-time unsupervised clustering algorithms applied to high-throughput cloud telemetry, achieving over 99.4% precision in catching infrastructure latency anomalies and resource contention.",
        "tags": ["Anomaly Detection", "Cloud Applications", "Unsupervised Learning", "Telemetry Analysis", "High Throughput"],
        "bibtex": """@article{verma2024anomalydetection,
  title={AI-Powered Anomaly Detection in Cloud-Based Applications},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={12},
  number={1},
  pages={ec07},
  year={2024},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v12i01.ec07}
}"""
    },
    {
        "id": "pub-19",
        "title": "Secure AI Systems: Protecting Machine Learning Models from Emerging Cyber Threats",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2025",
        "volume": "Vol. 13, No. 10",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v13i10.ec04",
        "link": "https://www.ijsrm.net/index.php/ijsrm/article/view/6677",
        "publisher": "IJSRM",
        "abstract": "Examines model extraction, membership inference, and training pipeline data poisoning vectors, formulating cryptographic watermarking and differential privacy bounds to preserve proprietary model integrity.",
        "tags": ["Model Protection", "Data Poisoning", "Differential Privacy", "Membership Inference", "Model Extraction"],
        "bibtex": """@article{verma2025securesystems,
  title={Secure AI Systems Protecting Machine Learning Models from Emerging Cyber Threats},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={13},
  number={10},
  pages={ec04},
  year={2025},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v13i10.ec04}
}"""
    },
    {
        "id": "pub-20",
        "title": "Adversarial Machine Learning: Security Risks and Defense Strategies in AI-Driven Applications",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 2",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v14i02.ec04",
        "link": "https://www.ijsrm.net/index.php/ijsrm/article/view/7002",
        "publisher": "IJSRM",
        "abstract": "Comprehensive analysis of perturbation-based evasion attacks against vision, NLP, and tabular classifiers, detailing certified robust optimization and randomized smoothing defenses.",
        "tags": ["Adversarial ML", "Defense Strategies", "Robust Optimization", "Evasion Attacks", "Certified Robustness"],
        "bibtex": """@article{verma2026adversarialml,
  title={Adversarial Machine Learning: Security Risks and Defense Strategies in AI-Driven Applications},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={2},
  pages={ec04},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i02.ec04}
}"""
    },
    {
        "id": "pub-21",
        "title": "Blockchain-Enabled Artificial Intelligence and AI Agents for Secure Data Sharing and Cybersecurity Applications",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 8",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "security",
        "topic_label": "AI Security & Trust",
        "doi": "10.18535/ijsrm/v14i08.ec03",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/7958",
        "publisher": "IJSRM",
        "abstract": "Combines decentralized ledger smart contracts with autonomous AI agents to construct zero-knowledge verifiable audit trails and secure cross-organizational data federation networks.",
        "tags": ["Blockchain AI", "Decentralized Agents", "Secure Data Sharing", "Smart Contracts", "Audit Trails"],
        "bibtex": """@article{verma2026blockchainai,
  title={Blockchain-Enabled Artificial Intelligence and AI Agents for Secure Data Sharing and Cybersecurity Applications},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={8},
  pages={ec03},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i08.ec03}
}"""
    },
    {
        "id": "pub-22",
        "title": "Automated Vulnerability Patching in Legacy Code Using LLMs and Multi-AI Agents",
        "venue": "International Journal of Scientific Research and Management (IJSRM)",
        "year": "2026",
        "volume": "Vol. 14, No. 4",
        "authors": "Harsh Verma",
        "category": "journal",
        "category_label": "Journal Article",
        "topic": "agents",
        "topic_label": "AI Agentic Systems",
        "doi": "10.18535/ijsrm/v14i04.ec05",
        "link": "https://ijsrm.net/index.php/ijsrm/article/view/7194",
        "publisher": "IJSRM",
        "abstract": "Introduces an autonomous agentic refactoring engine that parses legacy codebases, pinpoints security vulnerabilities, synthesizes semantic patches using LLMs, and verifies regression-free builds with automated fuzzing suites.",
        "tags": ["Legacy Code Patching", "LLMs", "Multi-Agent Automation", "Security Vulnerabilities", "Automated Fuzzing"],
        "bibtex": """@article{verma2026automatedpatching,
  title={Automated Vulnerability Patching in Legacy Code Using LLMs and Multi-AI Agents},
  author={Verma, Harsh},
  journal={International Journal of Scientific Research and Management},
  volume={14},
  number={4},
  pages={ec05},
  year={2026},
  publisher={IJSRM},
  doi={10.18535/ijsrm/v14i04.ec05}
}"""
    }
]

with open('papers_data.json', 'w') as f:
    json.dump(papers, f, indent=2)
print(f"Saved {len(papers)} papers.")
