#!/usr/bin/env python3
"""
scripts/sync_site_stats.py
===========================
Single source of truth synchronizer for Harsh Verma's portfolio metrics.
Ensures research paper counts, awards counts, book counts, patents,
media features, and verified profile metrics remain uniform, accurate,
and up-to-date across all HTML pages, templates, scripts, and server code.

Usage:
    python3 scripts/sync_site_stats.py
"""

import os
import re
import json

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def load_canonical_stats():
    # 1. Papers count from papers_data.json
    papers_path = os.path.join(ROOT_DIR, "papers_data.json")
    if os.path.exists(papers_path):
        with open(papers_path, "r", encoding="utf-8") as f:
            papers = json.load(f)
            papers_count = len(papers)
    else:
        papers_count = 25

    # 2. Awards count from awards_data.json
    awards_path = os.path.join(ROOT_DIR, "awards_data.json")
    if os.path.exists(awards_path):
        with open(awards_path, "r", encoding="utf-8") as f:
            awards = json.load(f)
            awards_count = len(awards)
    else:
        awards_count = 25

    # 3. Media items count from media_data.json
    media_path = os.path.join(ROOT_DIR, "media_data.json")
    if os.path.exists(media_path):
        with open(media_path, "r", encoding="utf-8") as f:
            media = json.load(f)
            media_count = len(media)
    else:
        media_count = 40

    return {
        "papers_count": papers_count,
        "papers_display": f"{papers_count}+",
        "awards_count": awards_count,
        "awards_display": f"{awards_count}",
        "awards_display_plus": f"{awards_count}+",
        "books_count": 2,
        "books_reviewed": 6,
        "patents_count": 6,
        "media_count": media_count,
        "media_display": f"{media_count}+",
        "profiles_count": 47,
        "profiles_display": "47"
    }

def update_client_stats_js(stats):
    js_path = os.path.join(ROOT_DIR, "js", "hv-site-stats.js")
    content = f"""/**
 * hv-site-stats.js
 * Single source of truth client-side metrics binder for Harsh Verma Portfolio.
 * Auto-generated by scripts/sync_site_stats.py. Do not edit manually.
 */
(function() {{
    'use strict';

    window.HV_SITE_STATS = {{
        researchPapers: {stats['papers_count']},
        researchPapersDisplay: "{stats['papers_display']}",
        awardsCount: {stats['awards_count']},
        awardsDisplay: "{stats['awards_display']}",
        awardsDisplayPlus: "{stats['awards_display_plus']}",
        booksCount: {stats['books_count']},
        booksReviewed: {stats['books_reviewed']},
        patentsCount: {stats['patents_count']},
        mediaCount: {stats['media_count']},
        mediaDisplay: "{stats['media_display']}",
        profilesCount: {stats['profiles_count']}
    }};

    function applyStatsToDOM() {{
        var s = window.HV_SITE_STATS;

        // 1. Research Papers
        document.querySelectorAll('[data-stat="research-papers"]').forEach(function(el) {{
            el.textContent = s.researchPapersDisplay;
        }});
        document.querySelectorAll('[data-stat="research-papers-raw"]').forEach(function(el) {{
            el.textContent = s.researchPapers;
        }});
        document.querySelectorAll('[data-stat="research-papers-link"]').forEach(function(el) {{
            el.innerHTML = '<i class="mdi mdi-school mr-1"></i> View ' + s.researchPapersDisplay + ' Published Papers &rarr;';
        }});

        // 2. Awards
        document.querySelectorAll('[data-stat="awards-count"]').forEach(function(el) {{
            el.textContent = s.awardsDisplay;
        }});
        document.querySelectorAll('[data-stat="awards-count-plus"]').forEach(function(el) {{
            el.textContent = s.awardsDisplayPlus;
        }});

        // 3. Media Features
        document.querySelectorAll('[data-stat="media-count"]').forEach(function(el) {{
            el.textContent = s.mediaDisplay;
        }});

        // 4. Books
        document.querySelectorAll('[data-stat="authored-books"]').forEach(function(el) {{
            el.textContent = s.booksCount;
        }});
        document.querySelectorAll('[data-stat="books-reviewed"]').forEach(function(el) {{
            el.textContent = s.booksReviewed;
        }});

        // 5. Patents
        document.querySelectorAll('[data-stat="patents-count"]').forEach(function(el) {{
            el.textContent = s.patentsCount;
        }});
    }}

    if (document.readyState === 'loading') {{
        document.addEventListener('DOMContentLoaded', applyStatsToDOM);
    }} else {{
        applyStatsToDOM();
    }}
}})();
"""
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Updated {js_path} with {stats['papers_display']} papers, {stats['awards_count']} awards, {stats['media_display']} media.")

def sync_html_and_generators(stats):
    p_num = str(stats["papers_count"])
    p_disp = stats["papers_display"]
    a_num = str(stats["awards_count"])
    a_disp_plus = stats["awards_display_plus"]
    m_num = str(stats["media_count"])
    m_disp = stats["media_display"]
    prof_num = str(stats["profiles_count"])

    target_extensions = (".html", ".py", ".js", ".ts", ".json")
    updated_files = []

    for root, dirs, files in os.walk(ROOT_DIR):
        if "node_modules" in root or ".git" in root or "bun.lock" in root:
            continue
        for filename in files:
            if not filename.endswith(target_extensions):
                continue
            filepath = os.path.join(root, filename)
            
            # Skip this script itself and data files that define the sources
            if os.path.abspath(filepath) == os.path.abspath(__file__):
                continue
            if filename in ("papers_data.json", "awards_data.json", "media_data.json"):
                continue

            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    content = f.read()
            except Exception:
                continue

            original = content

            # --- PAPERS METRICS ---
            # 1. Update "View XX+ Published Papers" links
            content = re.sub(
                r'(\bView\s+)\d+\+?(\s+Published Papers\s*&rarr;)',
                rf'\g<1>{p_disp}\g<2>',
                content
            )

            # 2. Update author-stat-card research papers stat-val
            content = re.sub(
                r'(<div class="stat-val"(?:[^>]*)>)\s*\d+\+?\s*(</div>\s*<div class="stat-lbl">\s*Research Papers\s*</div>)',
                rf'\g<1>{p_disp}\g<2>',
                content
            )

            # 3. Update "XX+ IEEE publications" or "XX+ IEEE & peer-reviewed publications"
            content = re.sub(
                r'\b\d+\+?\s+IEEE\b(?:\s+(?:&amp;|&)\s+peer-reviewed)?\s+publications',
                f'{p_disp} IEEE &amp; peer-reviewed publications',
                content
            )

            # 4. Update "Browse XX+ Published Papers"
            content = re.sub(
                r'(\bBrowse\s+)\d+\+?(\s+Published Papers\b)',
                rf'\g<1>{p_disp}\g<2>',
                content
            )

            # 5. Update "Google Scholar (XX+ Papers)"
            content = re.sub(
                r'(Google Scholar\s*\()\d+\+?(\s*Papers\))',
                rf'\g<1>{p_disp}\g<2>',
                content
            )

            # 6. Update "Showing all XX publications" in publications page
            content = re.sub(
                r'(\bShowing all\s+)\d+(\s+publications\b)',
                rf'\g<1>{p_num}\g<2>',
                content
            )

            # 7. Update "View All XX Publications & 6 Patents" in index.html
            content = re.sub(
                r'(\bView All\s+)\d+(\s+Publications\s*(?:&amp;|&)\s*6\s*Patents\b)',
                rf'\g<1>{p_num}\g<2>',
                content
            )

            # 8. Update quick ribbon "<h3...>XX+</h3>...Peer-Reviewed Papers"
            content = re.sub(
                r'(<h3[^>]*>)\s*\d+\+?\s*(</h3>\s*<span[^>]*>\s*Peer-Reviewed Papers\s*</span>)',
                rf'\g<1>{p_disp}\g<2>',
                content
            )

            # 9. Update data-stat="research-papers" and data-stat="research-papers-raw"
            content = re.sub(
                r'(data-stat="research-papers"[^>]*>)\s*\d+\+?\s*(</)',
                rf'\g<1>{p_disp}\g<2>',
                content
            )
            content = re.sub(
                r'(<[^>]+data-stat="research-papers-raw"[^>]*>)\s*\d+\s*(</)',
                rf'\g<1>{p_num}\g<2>',
                content
            )

            # 10. Update filter buttons "All Papers (XX)"
            content = re.sub(
                r'(data-filter="all">All Papers\s*\()\d+(\))',
                rf'\g<1>{p_num}\g<2>',
                content
            )

            # 11. Update scholar-stat-papers
            content = re.sub(
                r'(id="scholar-stat-papers"[^>]*>[\s\S]*?<div class="scholar-stat-number"[^>]*>)\s*\d+\+?\s*(</div>[\s\S]*?<div class="scholar-stat-label">\s*Published &amp; Forthcoming Papers)',
                rf'\g<1>{p_num}\g<2>',
                content
            )

            # --- AWARDS & HONORS METRICS ---
            # 12. Update "24+ Honors" or "24+ Global Honors & Citations"
            content = re.sub(
                r'(\b(?:24|24\+)\s+Global Honors\s*(?:&amp;|&)\s*Citations\b)',
                f'{a_disp_plus} Global Honors &amp; Citations',
                content
            )
            content = re.sub(
                r'(<div class="home-metric-value"[^>]*><i class="mdi mdi-trophy-variant-outline mr-1 text-warning"></i>)\s*24\+?\s*(</div>)',
                rf'\g<1>{a_disp_plus}\g<2>',
                content
            )

            # 13. Update "Looking for All 24+ Verified Honors & Fellowships?"
            content = re.sub(
                r'Looking for All\s+24\+?\s+Verified Honors',
                f'Looking for All {a_disp_plus} Verified Honors',
                content
            )

            # 14. Update "View Full 24+ Awards" and "View All 24 Awards"
            content = re.sub(
                r'(\bView Full\s+)24\+?(\s+Awards\b)',
                rf'\g<1>{a_disp_plus}\g<2>',
                content
            )
            content = re.sub(
                r'(\bView All\s+)24(\s+Awards\b)',
                rf'\g<1>{a_num}\g<2>',
                content
            )

            # 15. Update "24 Prestigious Global Awards & Honors"
            content = re.sub(
                r'24\s+Prestigious Global Awards\s*&amp;\s*Honors',
                f'{a_num} Prestigious Global Awards &amp; Honors',
                content
            )
            content = re.sub(
                r'24\s+Prestigious Global Awards\s*&\s*Honors',
                f'{a_num} Prestigious Global Awards & Honors',
                content
            )
            content = re.sub(
                r'\b24\s+international awards and recognitions\b',
                f'{a_num} international awards and recognitions',
                content
            )
            content = re.sub(
                r'\b24\s+Global Awards\b',
                f'{a_num} Global Awards',
                content
            )
            content = re.sub(
                r'\b24\s+Prestigious Recognitions\b',
                f'{a_num} Prestigious Recognitions',
                content
            )
            content = re.sub(
                r'\b24\s+Prestigious Awards\b',
                f'{a_num} Prestigious Awards',
                content
            )

            # 16. Update "earned 24 global technology honors" & "recipient of 24 international honors"
            content = re.sub(
                r'\bearned\s+24\s+global technology honors\b',
                f'earned {a_num} global technology honors',
                content
            )
            content = re.sub(
                r'\brecipient of\s+24\s+international honors\b',
                f'recipient of {a_num} international honors',
                content
            )

            # 17. Update copilot placeholder and status line
            content = re.sub(
                r'(\bAsk about Harsh\'s AI books,\s*)24(\s*awards,\s*papers,\s*or\s*speaking\b)',
                rf'\g<1>{a_num}\g<2>',
                content
            )
            content = re.sub(
                r'Grounded in\s*24\s*Awards,\s*Books',
                f'Grounded in {a_num} Awards, Books',
                content
            )
            content = re.sub(
                r'\bawardsCount:\s*24\b',
                f'awardsCount: {a_num}',
                content
            )

            # --- VERIFIED PROFILES METRICS ---
            # 18. Update navbar dropdown "42 Verified Profiles Hub" -> "47 Verified Profiles Hub"
            content = re.sub(
                r'(<span class="dropdown-item-title">)\s*(?:38|42|52)\+?\s*Verified Profiles Hub\s*(</span>)',
                rf'\g<1>{prof_num} Verified Profiles Hub\g<2>',
                content
            )

            # 19. Update "38 Verified Academic & Industry Hubs" / "38 Verified Academic/Professional Registries"
            content = re.sub(
                r'\b(?:38|42)\s+Verified Academic\s*(?:&amp;|&)\s*Industry Hubs\b',
                f'{prof_num} Verified Academic &amp; Industry Hubs',
                content
            )
            content = re.sub(
                r'\b(?:38|42)\s+Verified Academic/Professional Registries\b',
                f'{prof_num} Verified Academic/Professional Registries',
                content
            )

            # 20. Update "52+ Verified Profiles" in index.html biography CTA
            content = re.sub(
                r'Full Biography\s*(?:&amp;|&)\s*(?:38|42|52)\+?\s*Verified Profiles',
                f'Full Biography &amp; {prof_num} Verified Profiles',
                content
            )

            # --- MEDIA & PRESS METRICS ---
            # 21. Update "39+ Global Press Features" / "39+ Features"
            content = re.sub(
                r'(<h3[^>]*>)\s*39\+?\s*(</h3>\s*<span[^>]*>\s*Global Press Features\s*</span>)',
                rf'\g<1>{m_disp}\g<2>',
                content
            )
            content = re.sub(
                r'\b39\+?\s+Features\s*•\s*7\s*Premier Platforms',
                f'{m_disp} Features • 7 Premier Platforms',
                content
            )
            content = re.sub(
                r'across\s+\*\*39\+?\s+media features\*\*',
                f'across **{m_disp} media features**',
                content
            )

            # --- PATENTS METRICS ---
            # 22. Update "Patents (1 Granted, 4 In Process)" in publications page
            content = re.sub(
                r'Patents \(1 Granted,\s*4 In Process\)',
                'Patents (1 Granted, 1 Published, 4 Pending)',
                content
            )

            # 23. Ensure hv-site-stats.js is included in HTML files
            if filepath.endswith(".html") and "js/hv-site-stats.js" not in content and "</body>" in content:
                content = content.replace("</body>", "    <script src=\"js/hv-site-stats.js\"></script>\n</body>")

            if content != original:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                rel_path = os.path.relpath(filepath, ROOT_DIR)
                updated_files.append(rel_path)

    return updated_files

def main():
    print("--- Harmonizing Portfolio Metrics Across Site ---")
    stats = load_canonical_stats()
    print(f"Canonical Research Papers Count: {stats['papers_count']} ({stats['papers_display']})")
    print(f"Canonical Awards Count: {stats['awards_count']} ({stats['awards_display_plus']})")
    print(f"Canonical Media Features Count: {stats['media_count']} ({stats['media_display']})")
    print(f"Canonical Verified Profiles Count: {stats['profiles_count']}")
    
    update_client_stats_js(stats)
    updated = sync_html_and_generators(stats)
    
    print(f"Synchronized {len(updated)} files:")
    for f in updated:
        print(f"  - {f}")
    print("Site statistics synchronization completed successfully.")

if __name__ == "__main__":
    main()
